DELETE FROM accounts;
INSERT INTO accounts (
    id,
    login_id,
    password,
    role,
    status,
    failed_login_attempts,
    requires_password_change,
    created_at,
    updated_at
) VALUES
      (
          1,
          '26001001',
          '$2a$10$GoVsP4BH9AsO74rttdEiu.bf2h0oebo/i9214C7W.1Kj7kmU3vHES',
          'STUDENT',
          'ACTIVE',
          0,
          TRUE,
          NOW(),
          NOW()
      ),
      (
          2,
          'p26001001',
          '$2a$10$GoVsP4BH9AsO74rttdEiu.bf2h0oebo/i9214C7W.1Kj7kmU3vHES',
          'PROFESSOR',
          'ACTIVE',
          0,
          TRUE,
          NOW(),
          NOW()
      ),
      (
          3,
          'a26001001',
          '$2a$10$GoVsP4BH9AsO74rttdEiu.bf2h0oebo/i9214C7W.1Kj7kmU3vHES',
          'ADMIN',
          'ACTIVE',
          0,
          FALSE,
          NOW(),
          NOW()
      );